### ISSUE TITLE
Add Utility Styling For Heading and Paragraph 

### ISSUE THREAD

**Issue by Evavic44** [chryz-hub/chryz-hub.github.io#157]
> ### What this Feat does

_Creates Reusable markup for styling the website quickly and efficiently._

> ### Proposed changes: 
- [x] _Add a class for headings_
```css
.text-primary {
   font-size: 1.3rem;
   padding-bottom: 8px;
}
```
- [x] _Add a class for paragraphs_
```css
.text-secondary {
  font-size: 0.97rem;
  font-weight: 300;
  margin: 0 15px;
  line-height: 1.7;
  padding-bottom: 15px;
}
```
> ### Location for changes
Add to the `global.css` file
