### ISSUE TITLE
Add Global Styling For buttons

### ISSUE THREAD

**Issue by Evavic44** [chryz-hub/chryz-hub.github.io#158]
> ### What this Feat does

_Create reusable global styling for buttons_

> ### Proposed changes

- [x]  _Create main button_
```css
.btn {
  display: inline-block;
  padding: 15px 20px;
  font-size: 0.97rem;
  cursor: pointer;
  border: none;
  transition: background 0.4s ease-in-out;
  background-color: var(--darkBackground);
  color: #fff;
}
```

- [x]  _Create primary button_
```css {
.btn-primary {
  background-color: var(--primaryBtn);
  color: #fff;
  padding: 18px 30px;
  border-radius: 5px;
}
```

- [x]  _Create secondary button_
```css {
.btn-secondary{
  background-color: var(--secondaryBtn);
  color: #fff;
  padding: 18px 30px;
  border-radius: 5px;
}
```
### _**Please work on one change so others can contribute too.**_
